// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ornzueeyhpuqcpszvtco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ybnp1ZWV5aHB1cWNwc3p2dGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mzc3MDIsImV4cCI6MjA2MzMxMzcwMn0.EfE4Tsw4Hn_YZ-eBm7kal19fMr0-Aqs36wK-baDFeuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);